[package]
name = "hulk-codegen"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
hulk-banner = { path = "../hulk-banner" }
hulk-diagnostics = { path = "../hulk-diagnostics" }
hulk-hir = { path = "../hulk-hir" }
inkwell = { workspace = true }

[dev-dependencies]
hulk-diagnostics = { path = "../hulk-diagnostics" }
hulk-driver = { path = "../hulk-driver" }
