[package]
name = "hulk-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[[bin]]
name = "hulkc"
path = "src/main.rs"

[[bin]]
name = "hulk"
path = "src/bin/hulk.rs"

[dependencies]
hulk-driver = { path = "../hulk-driver" }
clap = { workspace = true, features = ["derive"] }
