[package]
name = "hulk-hir"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
hulk-ast = { path = "../hulk-ast" }
hulk-semantic = { path = "../hulk-semantic" }
hulk-types = { path = "../hulk-types" }

[dev-dependencies]
hulk-diagnostics = { path = "../hulk-diagnostics" }
hulk-lexer = { path = "../hulk-lexer" }
hulk-parser = { path = "../hulk-parser" }
proptest.workspace = true
